apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "argocd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "argocd.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: argocd-server
          image: argoproj/argocd:v2.7.0  # or any specific version you need
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ARGOCD_SERVER_REPLICAS
              value: "1"
