apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "argocd.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.server.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "argocd.fullname" . }}-server
                port:
                  number: 443
