apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "argocd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "argocd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.server.service.type }}
